// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taqlambjhpijndqlzyxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhcWxhbWJqaHBpam5kcWx6eXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDU0MTQsImV4cCI6MjA2MDEyMTQxNH0.1xaFIA5yrsSrZd4ug7UdWZZ2U0NP7Sq-4ISPZWcWF4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);